CREATE TABLE IF NOT EXISTS bodega_articulos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  codigo VARCHAR(80) NULL,
  nombre VARCHAR(180) NOT NULL,
  tipo_articulo ENUM('REPUESTO','CONSUMIBLE','HERRAMIENTA','OTRO') NOT NULL DEFAULT 'REPUESTO',
  categoria VARCHAR(100) NULL,
  marca VARCHAR(100) NULL,
  numero_parte VARCHAR(120) NULL,
  tipo_unidad VARCHAR(120) NULL,
  unidad_medida VARCHAR(30) NOT NULL DEFAULT 'UND',
  stock_actual DECIMAL(12,2) NOT NULL DEFAULT 0,
  stock_minimo DECIMAL(12,2) NOT NULL DEFAULT 0,
  stock_maximo DECIMAL(12,2) NOT NULL DEFAULT 0,
  ubicacion VARCHAR(120) NULL,
  precio_unitario DECIMAL(12,2) NOT NULL DEFAULT 0,
  proveedor_id INT NULL,
  proveedor_nombre VARCHAR(180) NULL,
  fecha_ultima_compra DATE NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  creado_por INT NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_bodega_codigo (codigo),
  INDEX idx_bodega_articulo_nombre (nombre),
  INDEX idx_bodega_articulo_categoria (categoria),
  INDEX idx_bodega_articulo_tipo (tipo_articulo),
  INDEX idx_bodega_articulo_stock (stock_actual, stock_minimo),
  INDEX idx_bodega_articulo_proveedor (proveedor_id)
);

CREATE TABLE IF NOT EXISTS bodega_entregas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  placa VARCHAR(50) NULL,
  mecanico VARCHAR(120) NULL,
  tipo_trabajo ENUM('MANTENIMIENTO','CORRECTIVO','REPARACION','EMERGENCIA','OTRO') NOT NULL DEFAULT 'MANTENIMIENTO',
  observacion TEXT NULL,
  creado_por INT NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_bodega_entrega_placa (placa),
  INDEX idx_bodega_entrega_mecanico (mecanico),
  INDEX idx_bodega_entrega_fecha (creado_en)
);

CREATE TABLE IF NOT EXISTS bodega_prestamos_herramientas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  articulo_id INT NOT NULL,
  mecanico VARCHAR(120) NOT NULL,
  placa VARCHAR(50) NULL,
  cantidad DECIMAL(12,2) NOT NULL DEFAULT 1,
  estado ENUM('PRESTADO','DEVUELTO') NOT NULL DEFAULT 'PRESTADO',
  salida_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  devolucion_en TIMESTAMP NULL,
  recibido_por VARCHAR(120) NULL,
  observacion TEXT NULL,
  creado_por INT NULL,
  actualizado_por INT NULL,
  INDEX idx_bodega_prestamo_articulo (articulo_id),
  INDEX idx_bodega_prestamo_estado (estado),
  INDEX idx_bodega_prestamo_mecanico (mecanico),
  INDEX idx_bodega_prestamo_placa (placa)
);

CREATE TABLE IF NOT EXISTS bodega_movimientos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  articulo_id INT NOT NULL,
  entrega_id INT NULL,
  prestamo_id INT NULL,
  tipo_movimiento ENUM('ENTRADA','SALIDA','DEVOLUCION','AJUSTE','PRESTAMO','DEVOLUCION_HERRAMIENTA') NOT NULL,
  cantidad DECIMAL(12,2) NOT NULL,
  existencia_anterior DECIMAL(12,2) NOT NULL DEFAULT 0,
  existencia_nueva DECIMAL(12,2) NOT NULL DEFAULT 0,
  placa VARCHAR(50) NULL,
  mecanico VARCHAR(120) NULL,
  tipo_trabajo VARCHAR(50) NULL,
  proveedor_id INT NULL,
  proveedor_nombre VARCHAR(180) NULL,
  numero_factura VARCHAR(120) NULL,
  orden_compra_id INT NULL,
  precio_unitario DECIMAL(12,2) NOT NULL DEFAULT 0,
  motivo TEXT NULL,
  creado_por INT NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_bodega_mov_articulo (articulo_id),
  INDEX idx_bodega_mov_entrega (entrega_id),
  INDEX idx_bodega_mov_tipo (tipo_movimiento),
  INDEX idx_bodega_mov_placa (placa),
  INDEX idx_bodega_mov_fecha (creado_en),
  INDEX idx_bodega_mov_proveedor (proveedor_id)
);
