CREATE TABLE IF NOT EXISTS gastos_operativos (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  fuente VARCHAR(40) NOT NULL,
  fuente_id BIGINT NOT NULL,
  detalle_id BIGINT NOT NULL DEFAULT 0,
  fecha DATE NOT NULL,
  periodo CHAR(7) NOT NULL,
  placa VARCHAR(50) NULL,
  sede VARCHAR(120) NULL,
  negocio VARCHAR(80) NULL,
  tipo_unidad VARCHAR(80) NULL,
  rubro VARCHAR(80) NOT NULL,
  tipo_trabajo VARCHAR(30) NOT NULL DEFAULT 'CORRECTIVO',
  proveedor VARCHAR(180) NULL,
  descripcion TEXT NULL,
  cantidad DECIMAL(14,4) NOT NULL DEFAULT 1,
  precio_unitario DECIMAL(14,4) NOT NULL DEFAULT 0,
  monto DECIMAL(14,4) NOT NULL DEFAULT 0,
  estado VARCHAR(40) NOT NULL DEFAULT 'ACTIVO',
  creado_por INT NULL,
  metadata JSON NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_gastos_operativos_fuente (fuente, fuente_id, detalle_id),
  INDEX idx_gastos_operativos_periodo (periodo),
  INDEX idx_gastos_operativos_fecha (fecha),
  INDEX idx_gastos_operativos_placa (placa),
  INDEX idx_gastos_operativos_sede (sede),
  INDEX idx_gastos_operativos_negocio (negocio),
  INDEX idx_gastos_operativos_rubro (rubro),
  INDEX idx_gastos_operativos_tipo_trabajo (tipo_trabajo),
  INDEX idx_gastos_operativos_estado (estado)
);

CREATE TABLE IF NOT EXISTS auditoria_sistema (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  modulo VARCHAR(80) NOT NULL,
  tabla_afectada VARCHAR(80) NOT NULL,
  registro_id BIGINT NULL,
  accion VARCHAR(40) NOT NULL,
  resumen VARCHAR(255) NULL,
  antes JSON NULL,
  despues JSON NULL,
  usuario_id INT NULL,
  usuario_nombre VARCHAR(120) NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_auditoria_modulo_fecha (modulo, creado_en),
  INDEX idx_auditoria_tabla_registro (tabla_afectada, registro_id),
  INDEX idx_auditoria_usuario (usuario_id)
);
